---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: install docker
    yum: name=docker state=present
  - name: Start docker
    service: name=docker state=started
  - name: login docker hub
    command: docker login --username 04071988 --password North@123
  - name: deploy webapp
    command: docker run -itd -p 8383:80 --name c1 devopsedu/webapp
   

